### PR TITLE
Added a PackageReference wrapper called PackageReferenceEntity as the…

### PR DESCRIPTION
**Pull request by robgha01**
…re is some sort of problem with

the property  SemanticVersion in NuGet.PackageReference.

### CODE REVIEW

**Comment by gep13** [comment]
@robgha01 I have just tested this PR, and I don't think this solves the underlying problem.  How have you went about testing this?

**Comment by robgha01** [comment]
@gep13 i tested it with this

```
Task("Test")
    .Does(() =>
{
	var srcPath = new DirectoryPath("../BlueLeet.Build/");
	//var type = typeof(Cake.ExtendedNuGet.ExtendedNuGetAliases);	
	//MethodInfo GetPackageReferencesInfo = typeof(Cake.ExtendedNuGet.ExtendedNuGetAliases).GetMethod("GetPackageReferences", BindingFlags.Public | BindingFlags.Static);
	//var result = GetPackageReferencesInfo.Invoke(null, new[]{null, srcPath}) as IEnumerable<dynamic>;
	var result2 = GetPackageReferences(srcPath);

	foreach(var p in result2)
	{
		Information("PackageID:'{0}'", p.Id);
		Information("PackageVersion:'{0}'", p.Version);
		var t = new SemanticVersion(p.Version);
		Information("PackageVersion:'{0}'", t);
	}
});
```

**Comment by robgha01** [comment]
@gep13 This do not solve the actual bug somewhere in cake program i think but this is the test result i get this this wrapper. it would be nice if the underlying bug was found but its not an easy task.

image

**Comment by gep13** [comment]
Right, ok, so yes, the Unit Test that you have is working, but that was the case with the last PR that you sent through as well, right?  i.e. the Unit Test is not testing the Integration of the Addin with Cake (and nor should), however, there is definitely an issue with trying to run the Cake.ExtendedNuGet addin with Cake.

@Redth am I right in saying that you *only* use Mono when running Cake, or do you also use Roslyn?

**Comment by gep13** [comment]
@robgha01 can you zip up again the project that you are using where you were able to get the output from the above Test Task?  Based on some testing that I was doing last night with @patriksvensson I don't see how it is possible for this PR to actually have worked?!?  As a result, I am very confused.

**Comment by robgha01** [comment]
@gep13 here is the new zip: https://drive.google.com/file/d/0B1HsJ07Q3udPSGhYcnc2NVZCU1E/view?usp=sharing

**Comment by robgha01** [comment]
@gep13 And the modified Cake.ExtendedNuget method signatures

       ```
 [CakeMethodAlias]
        [CakeNamespaceImport("NuGet")]
        public static IEnumerable<PackageReferenceEntity> GetPackageReferences(this ICakeContext context, DirectoryPath path)
        {
            if (!path.IsRelative)
            {
                throw new CakeException("DirectoryPath must be relative!");
            }

            var packagePath = path.CombineWithFilePath(new FilePath("packages.config"));
            if (!System.IO.File.Exists(packagePath.FullPath))
            {
                throw new CakeException(string.Format("Could not find a packages.config file in '{0}'", path.FullPath));
            }

            var file = new PackageReferenceFile(packagePath.FullPath);
            return file.GetPackageReferences().Select(x => new PackageReferenceEntity(x));
        }

        [CakeMethodAlias]
        [CakeNamespaceImport("NuGet")]
        public static PackageReferenceEntity GetPackageReference(this ICakeContext context, DirectoryPath path, string packageId)
        {
            if (!path.IsRelative)
            {
                throw new CakeException("DirectoryPath must be relative!");
            }

            var packagePath = path.CombineWithFilePath(new FilePath("packages.config"));
            if (!System.IO.File.Exists(packagePath.FullPath))
            {
                throw new CakeException(string.Format("Could not find a packages.config file in '{0}'", path.FullPath));
            }

            var file = new PackageReferenceFile(packagePath.FullPath);
            return file.GetPackageReferences().Select(x => new PackageReferenceEntity(x)).FirstOrDefault(x => x.Id.Equals(packageId, StringComparison.OrdinalIgnoreCase));
        }
```

Wich uses
```
public class PackageReferenceEntity : IEquatable<PackageReferenceEntity>
    {
        public string Id { get; private set; }

        public string Version { get; private set; }

        public IVersionSpec VersionConstraint { get; set; }

        public FrameworkName TargetFramework { get; private set; }

        public bool IsDevelopmentDependency { get; private set; }

        public bool RequireReinstallation { get; private set; }

        public PackageReferenceEntity(PackageReference reference)
        {
            Id = reference.Id;
            Version = reference.Version.ToString();
            VersionConstraint = reference.VersionConstraint;
            TargetFramework = reference.TargetFramework;
            IsDevelopmentDependency = reference.IsDevelopmentDependency;
            RequireReinstallation = reference.RequireReinstallation;
        }

        public override bool Equals(object obj)
        {
            PackageReferenceEntity other = obj as PackageReferenceEntity;
            if (other != null)
            {
                return Equals(other);
            }

            return false;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode() * 3137 + (Version == null ? 0 : Version.GetHashCode());
        }

        public override string ToString()
        {
            if (Version == null)
            {
                return Id;
            }

            if (VersionConstraint == null)
            {
                return Id + " " + Version;
            }

            return Id + " " + Version + " (" + VersionConstraint + ")";
        }

        public bool Equals(PackageReferenceEntity other)
        {
            if (other == null)
            {
                return false;
            }

            if (Id.Equals(other.Id, StringComparison.OrdinalIgnoreCase))
            {
                return Version == other.Version;
            }

            return false;
        }
    }
```

**Comment by robgha01** [comment]
@gep13 The actual change was this property
Changed
`public SemanticVersion Version { get; private set; }`
to
`public string Version { get; private set; }`

**Comment by gep13** [comment]
@robgha1 have you always been using the Experimental flag for Cake, or is that something that you have recently added?

**Comment by robgha01** [comment]
@gep13 Yes i have always used it to get support for string interpolation $"{SomeVar}"

**Comment by gep13** [comment]
@robgha01 ok, that is the sort of information that we really need in order to help you in debugging issues like this.  A lot of my time, and @patriksvensson time, was wasted last night trying to reproduce the issue that you said you were seeing.  If you had mentioned that you were using `-experimental` then we might have been in a position to help sooner.

**Comment by robgha01** [comment]
@gep13 ok, i will keep that in mind in the future and sorry for the wasted time.

**Comment by gep13** [comment]
@Redth I think some more investigation is needed here before pulling this in.

Currently, the extended NuGet addin only works is you use `Experimental` or `Mono`.  Is that expected?  If you try to use Cake out of the box, there are exceptions, around this new aliases that were just added, and also the existing IsNuGetPublished aliases.

Is it expected that this addin will only work with using one of the two above modes?

**Comment by matkoch** [comment]
@Redth ping.

**Comment by Redth** [comment]
Sorry for the silence but I Think this issue is now outdated.  Please open a new issue if the newest version has weirdness here.

**Pull request closed without merging**
